services:
  traefik:
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "8080:0"
    volumes:
      - ./infra/traefik/traefik.prod.yml:/etc/traefik/traefik.yml:ro
      - letsencrypt_data:/letsencrypt

  db:
    restart: always

  api:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.services.api.loadbalancer.server.port=8000

  front:
    build:
      context: ./front
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.front.tls=true
      - traefik.http.routers.front.tls.certresolver=letsencrypt
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.services.front.loadbalancer.server.port=80
    networks:
      - ezlife

volumes:
  letsencrypt_data:
