services:
  traefik:
    command:
      - --configFile=/etc/traefik/traefik.yml
    volumes:
      - ./infra/traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - ./infra/traefik/dynamic.dev.yml:/etc/traefik/dynamic.yml:ro
      - ./infra/certs:/certs:ro

  api:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`local.ezlife.com`) && PathPrefix(`/api`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.services.api.loadbalancer.server.port=8000
    volumes:
      - ./api/app:/app/app:ro

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`local.ezlife.com`)
      - traefik.http.routers.front.tls=true
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.services.front.loadbalancer.server.port=5173
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      - ./front/index.html:/app/index.html
    networks:
      - ezlife
